rules:
  # === ENABLED ===
  unpinned-uses: {}
  ref-version-mismatch: {}
  unpinned-images: {}
  secrets-inherit: {}
  known-vulnerable-actions: {}
  cache-poisoning: {}
  github-env: {}
  insecure-commands: {}
  hardcoded-container-credentials: {}
  obfuscation: {}
  misfeature: {}
  bot-conditions: {}
  ref-confusion: {}
  impostor-commit: {}
  unredacted-secrets: {}
  unsound-condition: {}
  unsound-contains: {}
  use-trusted-publishing: {}
  forbidden-uses: {}
  archived-uses: {}
  dependabot-execution: {}
  dependabot-cooldown: {}
  concurrency-limits: {}
  overprovisioned-secrets: {}
  artipacked:
    disable: true
  excessive-permissions: {}
  template-injection: {}
  secrets-outside-env: {}
  dangerous-triggers: {}
  superfluous-actions: {}
