repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.102.0
    hooks:
      - id: terraform_fmt
      - id: terraform_validate
      - id: terraform_providers_lock
        args:
          - --hook-config=--mode=only-check-is-current-lockfile-cross-platform
      - id: terraform_tflint
        verbose: true
        args:
          - --hook-config=--delegate-chdir
          - --args=--config=__GIT_WORKING_DIR__/.tflint.hcl
          - --args=--fix
      - id: terraform_docs
        exclude: ^examples/complete/
        args:
          - --hook-config=--add-to-existing-file=true     # Boolean. true or false
          - --hook-config=--create-file-if-not-exist=true # Boolean. true or false