repos:
  ### General Hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: no-commit-to-branch
        args: [ '--branch', 'main' ]

  ### Github Action Hooks
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.35.0
    hooks:
      - id: check-github-workflows
        args: [ "--verbose" ]

  - repo: https://github.com/rhysd/actionlint
    rev: v1.7.9
    hooks:
      - id: actionlint
        files: ^\.github/workflows/

  ### Terraform Hooks
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.102.0
    hooks:
      - id: terraform_fmt
      - id: terraform_validate
      - id: terraform_providers_lock
        args:
          - --hook-config=--mode=only-check-is-current-lockfile-cross-platform
      - id: terraform_tflint
        verbose: true
        args:
          - --hook-config=--delegate-chdir
          - --args=--config=__GIT_WORKING_DIR__/.tflint.hcl
          - --args=--fix
      - id: terraform_docs
        exclude: ^examples/
        args:
          - --hook-config=--add-to-existing-file=true     # Boolean. true or false
          - --hook-config=--create-file-if-not-exist=true # Boolean. true or false